import type { Metadata } from "next";
import "./globals.css";
import NavBar, { Tab } from "./components/NavBar/NavBar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const tabs: Tab[] = [
    { name: "Tumour Types", link: "new-page" },
    { name: "Diagnose", link: "new-page" },
    { name: "Your Images", link: "new-page"},
    { name: "Our Story", link: "new-pasge"}
];

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`page-with-padding`}
            >
                <NavBar
                    tabs={tabs}
                />
                {children}
            </body>
        </html>
    );
}
